// <auto-generated />
namespace SecurityAssetManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BarcodeDataTypeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BarcodeDataTypeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202102191608112_BarcodeDataTypeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
